# Generated by Django 4.0.5 on 2022-07-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='goal',
            field=models.CharField(choices=[('NP', 'No poverty'), ('ZH', 'Zero hunger'), ('GHWB', 'Good health and well-being'), ('QE', 'Quality education'), ('GE', 'Gender equality'), ('CWS', 'Clean water and sanitation'), ('ACE', 'Affordable and clean energy'), ('DWEG', 'Decent work and economic growth'), ('III', 'Industry, innovation, and infrastructure'), ('RI', 'Reduces inequalities'), ('SCC', 'Sustainable cities and communities'), ('RCP', 'Responsible consumption & production'), ('CA', 'Climate action'), ('LW', 'Life below water'), ('LL', 'Life on land'), ('PJSI', 'Peace, justice, and strong institutions')], max_length=4),
        ),
    ]
